import type { Question } from '@/types/quiz';

export const module1Questions: { de: Question[]; en: Question[] } = {
  en: [
    {
      question: "What is CPython?",
      answers: [
        "It's the default, reference implementation of Python, written in the C language",
        "It's a programming language that is a superset of the C language, designed to produce Python-like performance with code written in C",
        "It's a programming language that is a superset of Python, designed to produce C-like performance with code written in Python",
        "It is the default, reference implementation of the C language, written in Python"
      ],
      correct: [0],
      multiSelect: false
    },
    {
      question: "What is the best definition of a script?",
      answers: [
        "It's a text file that contains instructions which make up a Python program",
        "It's an error message generated by the compiler",
        "It's a text file that contains sequences of zeroes and ones",
        "It's an error message generated by the interpreter"
      ],
      correct: [0],
      multiSelect: false
    },
    {
      question: "What are the four fundamental elements that make up a language?",
      answers: [
        "An alphabet, a lexis, a syntax, and semantics",
        "An alphabet, morphology, phonetics, and semantics",
        "An alphabet, phonetics, phonology, and semantics",
        "An alphabet, a lexis, phonetics, and semantics"
      ],
      correct: [0],
      multiSelect: false
    },
    {
      question: "What is true about compilation? (Select two answers)",
      answers: [
        "It tends to be faster than interpretation",
        "The code is converted directly into machine code executable by the processor",
        "Both you and the end user must have the compiler to run your code",
        "It tends to be slower than interpretation"
      ],
      correct: [0, 1],
      multiSelect: true
    },
    {
      question: "How do you call a command-line interpreter which lets you interact with your OS and execute Python commands?",
      answers: [
        "A console",
        "A compiler",
        "An editor",
        "Jython"
      ],
      correct: [0],
      multiSelect: false
    },
    {
      question: "Choose the true statements. (Select two answers)",
      answers: [
        "Python is a good choice for creating and executing tests for applications",
        "Python is free, open-source, and multiplatform",
        "Python 3 is backwards compatible with Python 2",
        "Python is a good choice for low-level programming, e.g., when you want to implement an effective driver"
      ],
      correct: [0, 1],
      multiSelect: true
    },
    {
      question: "What is machine code?",
      answers: [
        "A low-level programming language consisting of binary digits/bits that the computer reads and understands",
        "A medium-level programming language consisting of the assembly code designed for the computer processor",
        "A high-level programming language consisting of instruction lists that humans can read and understand",
        "A low-level programming language consisting of hexadecimal digits that make up high-level language instructions"
      ],
      correct: [0],
      multiSelect: false
    },
    {
      question: "What is the expected behavior of the following program?",
      code: "prin(\"Goodbye!\")",
      answers: [
        "The program will generate an error message on the screen",
        "The program will output <code>\"Goodbye!\"</code> to the screen",
        "The program will output <code>Goodbye!</code> to the screen",
        "The program will output <code>(„Goodbye!\")</code> to the screen"
      ],
      correct: [0],
      multiSelect: false
    },
    {
      question: "What is the expected behavior of the following program?",
      code: "print(\"Hello!\")",
      answers: [
        "The program will output <code>Hello!</code> to the screen",
        "The program will output <code>\"Hello!\"</code> to the screen",
        "The program will output <code>(\"Hello\")</code> to the screen",
        "The program will generate an error message on the screen"
      ],
      correct: [0],
      multiSelect: false
    },
    {
      question: "How do you call a file containing a program written in a high-level programming language?",
      answers: [
        "A source file",
        "A machine file",
        "A code file",
        "A target file"
      ],
      correct: [0],
      multiSelect: false
    }
  ],
  de: [
    {
      question: "Was ist CPython?",
      answers: [
        "Es ist die Standard-Referenzimplementierung der Sprache Python, geschrieben in der Sprache C",
        "Es ist eine Programmiersprache, die eine Obermenge der Sprache C ist und dafür entwickelt wurde, Python-ähnliche Leistung mit in C geschriebenem Code zu erzielen",
        "Es ist eine Programmiersprache, die eine Obermenge von Python ist und dafür entwickelt wurde, C-ähnliche Leistung mit in Python geschriebenem Code zu erzielen",
        "Es ist die Standard-Referenzimplementierung der Sprache C, geschrieben in Python"
      ],
      correct: [0],
      multiSelect: false
    },
    {
      question: "Was ist die beste Definition eines Skripts?",
      answers: [
        "Es ist eine Textdatei, die Anweisungen enthält, die ein Python-Programm bilden",
        "Es ist eine Fehlermeldung, die vom Compiler generiert wird",
        "Es ist eine Textdatei, die Sequenzen von Nullen und Einsen enthält",
        "Es ist eine Fehlermeldung, die vom Interpreter generiert wird"
      ],
      correct: [0],
      multiSelect: false
    },
    {
      question: "Was sind die vier grundlegenden Elemente, die eine Sprache ausmachen?",
      answers: [
        "Ein Alphabet, ein Lexikon, eine Syntax und Semantik",
        "Ein Alphabet, Morphologie, Phonetik und Semantik",
        "Ein Alphabet, Phonetik, Phonologie und Semantik",
        "Ein Alphabet, ein Lexikon, Phonetik und Semantik"
      ],
      correct: [0],
      multiSelect: false
    },
    {
      question: "Was trifft auf die Kompilierung zu? (Wähle zwei Antworten)",
      answers: [
        "Sie ist tendenziell schneller als die Interpretation",
        "Der Code wird direkt in Maschinencode umgewandelt, der vom Prozessor ausgeführt werden kann",
        "Sowohl Sie als auch der Endbenutzer müssen den Compiler haben, um Ihren Code auszuführen",
        "Sie ist tendenziell langsamer als die Interpretation"
      ],
      correct: [0, 1],
      multiSelect: true
    },
    {
      question: "Wie nennt man einen Befehlszeileninterpreter, mit dem Sie mit Ihrem Betriebssystem interagieren und Python-Befehle ausführen können?",
      answers: [
        "Eine Konsole",
        "Ein Compiler",
        "Ein Editor",
        "Jython"
      ],
      correct: [0],
      multiSelect: false
    },
    {
      question: "Wähle die wahren Aussagen. (Wähle zwei Antworten)",
      answers: [
        "Python ist eine gute Wahl zum Erstellen und Ausführen von Tests für Anwendungen",
        "Python ist kostenlos, Open-Source und plattformübergreifend",
        "Python 3 ist abwärtskompatibel mit Python 2",
        "Python ist eine gute Wahl für Low-Level-Programmierung, z.B. wenn Sie einen effizienten Treiber implementieren möchten"
      ],
      correct: [0, 1],
      multiSelect: true
    },
    {
      question: "Was ist Maschinencode?",
      answers: [
        "Eine Low-Level-Programmiersprache bestehend aus Binärziffern/Bits, die der Computer liest und versteht",
        "Eine Mid-Level-Programmiersprache bestehend aus Assemblercode, der für den Computerprozessor entwickelt wurde",
        "Eine High-Level-Programmiersprache bestehend aus Anweisungslisten, die Menschen lesen und verstehen können",
        "Eine Low-Level-Programmiersprache bestehend aus Hexadezimalziffern, die High-Level-Sprachanweisungen bilden"
      ],
      correct: [0],
      multiSelect: false
    },
    {
      question: "Was ist das erwartete Verhalten des folgenden Programms?",
      code: "prin(\"Goodbye!\")",
      answers: [
        "Das Programm wird eine Fehlermeldung auf dem Bildschirm ausgeben",
        "Das Programm wird <code>\"Goodbye!\"</code> auf dem Bildschirm ausgeben",
        "Das Programm wird <code>Goodbye!</code> auf dem Bildschirm ausgeben",
        "Das Programm wird <code>(Goodbye!)</code> auf dem Bildschirm ausgeben"
      ],
      correct: [0],
      multiSelect: false
    },
    {
      question: "Was ist das erwartete Verhalten des folgenden Programms?",
      code: "print(\"Hello!\")",
      answers: [
        "Das Programm wird <code>Hello!</code> auf dem Bildschirm ausgeben",
        "Das Programm wird <code>\"Hello!\"</code> auf dem Bildschirm ausgeben",
        "Das Programm wird <code>(\"Hello\")</code> auf dem Bildschirm ausgeben",
        "Das Programm wird eine Fehlermeldung auf dem Bildschirm ausgeben"
      ],
      correct: [0],
      multiSelect: false
    },
    {
      question: "Wie nennt man eine Datei, die ein Programm enthält, das in einer High-Level-Programmiersprache geschrieben wurde?",
      answers: [
        "Eine Quelldatei",
        "Eine Maschinendatei",
        "Eine Codedatei",
        "Eine Zieldatei"
      ],
      correct: [0],
      multiSelect: false
    }
  ]
};
